## ======================================================================
## resources
## ======================================================================

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource
- name: http
  type: docker-image
  source:
    repository: aequitas/http-resource

resources:
- name: gpdb_pr
  type: pull-request
  source:
    repository: mathildaMa/gpdb
#    uri: "https://gitee.com/fanwenchang/gpdb.git"
    base_branch: "6X_STABLE_concourse"
    access_token: "317b2660a9b8044c117d4db08d42cf45f9e0115e"
    ignore_paths:
    - gpdb-doc/*
    - README*

- name: gpdb6-centos7-build
  type: docker-image
  source:
    repository: pivotaldata/gpdb6-ubuntu18.04-build
    #repository: pivotaldata/gpdb6-centos7-build

- name: gpdb6-centos7-test
  type: docker-image
  source:
    #repository: pivotaldata/gpdb6-centos7-test
    repository: pivotaldata/gpdb6-ubuntu18.04-test

- name: python-centos7
  type: http
  source:
    index: http://45.76.203.55:80
    regex: 'python-(?P<version>[0-9\.-]*).tar.gz'
    uri: 'http://45.76.203.55:80/python-{version}.tar.gz'

jobs:
- name: compile_and_test_gpdb
  public: true
  max_in_flight: 10
  plan:
  - aggregate:
    - get: gpdb_pr
      trigger: true
      version: every
    - get: gpdb6-centos7-build
    - get: gpdb6-centos7-test
#    - get: libsigar-installer
#      resource: libsigar-centos7
    - get: python-tarball
      resource: python-centos7

#  - put: gpdb_pr
#    params:
#      path: gpdb_pr
#      status: pending
  - # "do" the remaining steps with these hooks:
    on_failure:
      put: gpdb_pr
      params:
        path: gpdb_pr
        status: failure
    on_success:
      put: report_pr_success
      resource: gpdb_pr
      params:
        path: gpdb_pr
        status: success
    do:
    - task: init gpdb_src  # Fetch tags and submodules, because the PR resource doesn't.
      image: gpdb6-centos7-build
      config:
        platform: linux
        run:
          path: bash
          args:
          - -c
          - |
            git clone gpdb_pr gpdb_src &&
            cd gpdb_src &&
            git fetch https://github.com/mathildaMa/gpdb.git --tags &&
            git submodule update --init --recursive
        inputs: [{ name: gpdb_pr }]
        outputs: [{ name: gpdb_src }]
    - task: compile_gpdb_centos7
      file: gpdb_pr/concourse/tasks/compile_gpdb.yml
      image: gpdb6-centos7-build
      params:
        CONFIGURE_FLAGS: ""
        TARGET_OS: ubuntu
        TARGET_OS_VERSION: 18.04 
        BLD_TARGETS: "clients loaders"
      timeout: 30m

